name: Deploy Timeline Data

on:
  push:
    branches:
      - main
    paths:
      - 'public/contributions/*.md'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node scripts/generate-timeline-data.js
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLISOL_ITTOLUCA }}'
          channelId: live
          projectId: flisol-ittoluca
          target: collaborative-timeline-data